
#define CLIP_BORDER	1
//40

//#define CLIP_LEFT	(CLIP_BORDER)
//#define CLIP_RIGHT	(239-CLIP_BORDER)
//#define CLIP_TOP	(CLIP_BORDER)
//#define CLIP_BOTTOM	(199-CLIP_BORDER)

//#define CLIP_LEFT	(CLIP_BORDER)
//#define CLIP_RIGHT	(239-CLIP_BORDER)
//#define CLIP_TOP	100
//#define CLIP_BOTTOM	(199-CLIP_BORDER)


//#define CLIP_LEFT	0
//#define CLIP_TOP	100

//#define CLIP_RIGHT	239
//#define CLIP_BOTTOM	199


#define CLIP_LEFT	5
#define CLIP_RIGHT	220
#define CLIP_TOP	40
#define CLIP_BOTTOM	128

#define USE_ACCURATE_CLIPPING
#define USE_BUFFERED_SCREEN

#define _ADR_SCREEN_BUFFER 7800
#define _ADR_SCREEN_MEMORY a000

#ifdef USE_BUFFERED_SCREEN
#define _ADR_DRAWING _ADR_SCREEN_BUFFER
#define ADR_DRAWING 0x7800
#else
#define _ADR_DRAWING _ADR_SCREEN_MEMORY
#define ADR_DRAWING 0xa000
#endif
